import { ErrorRecord } from '../types/common';
import { AirdropEvent } from '../types/extraction';
import { ExternalSystemItem, StatsFileObject } from '../types/loading';
import { WorkerAdapterOptions } from '../types/workers';

export interface UploaderFactoryInterface {
  event: AirdropEvent;
  options?: WorkerAdapterOptions;
}

/**
 * Generic result type for uploader operations that can either succeed with a response or fail with an error.
 * @template T The type of the successful response data
 */
export type UploaderResult<T> =
  | { response: T; error?: never }
  | { response?: never; error: unknown };

/**
 * Artifact is an interface that defines the structure of an artifact. Artifact is a file that is generated by the extractor and uploaded to ADaaS.
 */
export enum ArtifactDateField {
  OldestCreatedDate = 'oldest_created_date',
  NewestCreatedDate = 'newest_created_date',
  OldestModifiedDate = 'oldest_modified_date',
  NewestModifiedDate = 'newest_modified_date',
}

export interface Artifact {
  id: string;
  item_type: string;
  item_count: number;
  [ArtifactDateField.OldestCreatedDate]?: string;
  [ArtifactDateField.NewestCreatedDate]?: string;
  [ArtifactDateField.OldestModifiedDate]?: string;
  [ArtifactDateField.NewestModifiedDate]?: string;
}

export type ArtifactDateRanges = Pick<
  Artifact,
  | ArtifactDateField.OldestCreatedDate
  | ArtifactDateField.NewestCreatedDate
  | ArtifactDateField.OldestModifiedDate
  | ArtifactDateField.NewestModifiedDate
>;

/**
 * ArtifactsPrepareResponse is an interface that defines the structure of the response from the prepare artifacts endpoint.
 */
export interface ArtifactsPrepareResponse {
  url: string;
  id: string;
  form_data: {
    key: string;
    value: string;
  }[];
}

/**
 * ArtifactToUpload is an interface that defines the structure of the response from the get upload url endpoint.
 */
export interface ArtifactToUpload {
  upload_url: string;
  artifact_id: string;
  form_data: {
    key: string;
    value: string;
  }[];
}

/**
 * UploadResponse is an interface that defines the structure of the response from upload through Uploader.
 */
export interface UploadResponse {
  artifact?: Artifact;
  error?: ErrorRecord;
}

/**
 * StreamAttachmentsResponse is an interface that defines the structure of the response from the stream attachments through Uploader.
 */
export interface StreamAttachmentsResponse {
  ssorAttachments?: SsorAttachment[];
  error?: ErrorRecord;
}

/**
 * StreamResponse is an interface that defines the structure of the response from the stream of single attachment through Uploader.
 */
export interface StreamResponse {
  ssorAttachment?: SsorAttachment;
  error?: ErrorRecord;
}

/**
 * SsorAttachment is an interface that defines the structure of the SSOR attachment.
 */
export interface SsorAttachment {
  id: {
    devrev: string;
    external: string;
  };
  parent_id: {
    external: string;
  };
  actor_id?: {
    external: string;
  };
  inline?: boolean;
}

export interface StatsFileResponse {
  error?: ErrorRecord;
  statsFile?: StatsFileObject[];
}

export interface TransformerFileResponse {
  error?: ErrorRecord;
  transformerFile?: ExternalSystemItem[];
}
