import { ErrorRecord } from '../types/common';
import { AirSyncEvent } from '../types/extraction';
import { ExternalSystemItem, StatsFileObject } from '../types/loading';
import { WorkerAdapterOptions } from '../types/workers';

export interface UploaderFactoryInterface {
  event: AirSyncEvent;
  options?: WorkerAdapterOptions;
}

export type UploaderResult<T> =
  | { response: T; error?: never }
  | { response?: never; error: unknown };

export enum ArtifactDateField {
  OldestCreatedDate = 'oldest_created_date',
  NewestCreatedDate = 'newest_created_date',
  OldestModifiedDate = 'oldest_modified_date',
  NewestModifiedDate = 'newest_modified_date',
}

/** A file generated by the extractor and uploaded to AirSync. */
export interface Artifact {
  id: string;
  item_type: string;
  item_count: number;
  [ArtifactDateField.OldestCreatedDate]?: string;
  [ArtifactDateField.NewestCreatedDate]?: string;
  [ArtifactDateField.OldestModifiedDate]?: string;
  [ArtifactDateField.NewestModifiedDate]?: string;
}

export type ArtifactDateRanges = Pick<
  Artifact,
  | ArtifactDateField.OldestCreatedDate
  | ArtifactDateField.NewestCreatedDate
  | ArtifactDateField.OldestModifiedDate
  | ArtifactDateField.NewestModifiedDate
>;

/** Response from the prepare artifacts endpoint. */
export interface ArtifactsPrepareResponse {
  url: string;
  id: string;
  form_data: {
    key: string;
    value: string;
  }[];
}

/** Response from the get upload url endpoint. */
export interface ArtifactToUpload {
  upload_url: string;
  artifact_id: string;
  form_data: {
    key: string;
    value: string;
  }[];
}

export interface UploadResponse {
  artifact?: Artifact;
  error?: ErrorRecord;
}

export interface StreamAttachmentsResponse {
  ssorAttachments?: SsorAttachment[];
  error?: ErrorRecord;
}

/** Result of streaming a single attachment through Uploader. */
export interface StreamResponse {
  ssorAttachment?: SsorAttachment;
  error?: ErrorRecord;
}

export interface SsorAttachment {
  id: {
    devrev: string;
    external: string;
  };
  parent_id: {
    external: string;
  };
  actor_id?: {
    external: string;
  };
  inline?: boolean;
}

export interface StatsFileResponse {
  error?: ErrorRecord;
  statsFile?: StatsFileObject[];
}

export interface TransformerFileResponse {
  error?: ErrorRecord;
  transformerFile?: ExternalSystemItem[];
}
