import { ErrorRecord } from '../types/common';
import { AirSyncEvent } from '../types/extraction';
import { ExternalSystemItem, StatsFileObject } from '../types/loading';
import { WorkerAdapterOptions } from '../types/workers';

/**
 * Construction parameters used to create an Uploader instance.
 *
 * Used to supply the triggering event (platform endpoint, token, request id) and optional adapter options.
 */
export interface UploaderFactoryInterface {
  /** The AirSync event supplying the DevRev endpoint, service account token, and request id. */
  event: AirSyncEvent;
  /** Optional worker adapter options (e.g. local development and skip-confirmation flags). */
  options?: WorkerAdapterOptions;
}

/**
 * Generic result type for uploader operations that can either succeed with a response or fail with an error.
 * @template T The type of the successful response data
 */
export type UploaderResult<T> =
  | { response: T; error?: never }
  | { response?: never; error: unknown };

/**
 * Artifact is an interface that defines the structure of an artifact. Artifact is a file that is generated by the extractor and uploaded to AirSync.
 */
export interface Artifact {
  id: string;
  item_type: string;
  item_count: number;
}

/**
 * ArtifactsPrepareResponse is an interface that defines the structure of the response from the prepare artifacts endpoint.
 */
export interface ArtifactsPrepareResponse {
  url: string;
  id: string;
  form_data: {
    key: string;
    value: string;
  }[];
}

/**
 * ArtifactToUpload is an interface that defines the structure of the response from the get upload url endpoint.
 */
export interface ArtifactToUpload {
  upload_url: string;
  artifact_id: string;
  form_data: {
    key: string;
    value: string;
  }[];
}

/**
 * UploadResponse is an interface that defines the structure of the response from upload through Uploader.
 */
export interface UploadResponse {
  artifact?: Artifact;
  error?: ErrorRecord;
}

/**
 * StreamAttachmentsResponse is an interface that defines the structure of the response from the stream attachments through Uploader.
 */
export interface StreamAttachmentsResponse {
  ssorAttachments?: SsorAttachment[];
  error?: ErrorRecord;
}

/**
 * StreamResponse is an interface that defines the structure of the response from the stream of single attachment through Uploader.
 */
export interface StreamResponse {
  ssorAttachment?: SsorAttachment;
  error?: ErrorRecord;
}

/**
 * SsorAttachment is an interface that defines the structure of the SSOR attachment.
 */
export interface SsorAttachment {
  id: {
    devrev: string;
    external: string;
  };
  parent_id: {
    external: string;
  };
  actor_id?: {
    external: string;
  };
  inline?: boolean;
}

/**
 * Result of fetching and parsing a loading stats file artifact.
 *
 * Used to return the per-item-type stats produced by the loading phase, or an error if it could not be read.
 */
export interface StatsFileResponse {
  /** Error describing why the stats file could not be retrieved or parsed. */
  error?: ErrorRecord;
  /** Parsed stats file entries, one per item type. */
  statsFile?: StatsFileObject[];
}

/**
 * Result of fetching and parsing a transformer file artifact.
 *
 * Used to return the transformed external system items to be loaded into DevRev, or an error if it could not be read.
 */
export interface TransformerFileResponse {
  /** Error describing why the transformer file could not be retrieved or parsed. */
  error?: ErrorRecord;
  /** Parsed external system items to load. */
  transformerFile?: ExternalSystemItem[];
}
