services:
  localstack:
    image: localstack/localstack:latest
    container_name: adaas-localstack-oom
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-../tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      resources:
        limits:
          memory: 512M  # Constrain memory to 512MB to trigger OOM conditions
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  oom-test-runner:
    build:
      context: ..
      dockerfile: oom-tests/Dockerfile.oom-tests
    container_name: adaas-oom-test-runner
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - NODE_OPTIONS=--max-old-space-size=256  # Limit Node.js heap to 256MB
    volumes:
      - ../src:/app/src
      - .:/app/oom-tests
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - ../tsconfig.json:/app/tsconfig.json
      - ../jest.config.cjs:/app/jest.config.cjs
    deploy:
      resources:
        limits:
          memory: 384M  # Constrain test runner memory
        reservations:
          memory: 128M
    working_dir: /app
    command: ["npm", "run", "test:oom"]

  oom-monitor:
    image: alpine:latest
    container_name: adaas-oom-monitor
    depends_on:
      - localstack
      - oom-test-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: |
      sh -c "
        apk add --no-cache docker-cli &&
        while true; do
          echo '=== Memory Usage Stats ===' &&
          docker stats --no-stream --format 'table {{.Container}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.CPUPerc}}' adaas-localstack-oom adaas-oom-test-runner &&
          sleep 5
        done
      "

