const ERROR_PREFIX = 'ERROR_CODE';
const ERROR_DELIMITER = '=';

export const enum ExtractionCommonError {
  EXTERNAL_SYNC_UNIT_DELETED = `${ERROR_PREFIX}${ERROR_DELIMITER}EXTERNAL_SYNC_UNIT_DELETED`,
  EXTERNAL_SYNC_UNIT_DEACTIVATED = `${ERROR_PREFIX}${ERROR_DELIMITER}EXTERNAL_SYNC_UNIT_DEACTIVATED`,
  USER_DELETED = `${ERROR_PREFIX}${ERROR_DELIMITER}USER_DELETED`,
}
